global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "sim_app_prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"

  - job_name: "sim_app_springboot"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:8080" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "sim_app_node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]
