version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: sim_app_prometheus
    ports:
      - "8081:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - sim_app_network

  grafana:
    image: grafana/grafana
    container_name: sim_app_grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SING_UP=false
      - GF_SERVER_DOMAIN=localhost
      # enable logger
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug
      # pre-install extension
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3090:3000"
    networks:
      - sim_app_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: sim_app_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/roofs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"
    networks:
      - sim_app_network

networks:
  sim_app_network:
    driver: bridge
